const tracks = [
  // Angry Tracks
  {
    track: "angry_1.mp3",
    mood: "Angry",
    genre: "Rock",
    tempo: "Fast",
    era: "Recent",
    artist: "Rage Pulse",
    album: "Fire Within",
  },
  {
    track: "angry_2.mp3",
    mood: "Angry",
    genre: "Rock",
    tempo: "Medium",
    era: "80-90s",
    artist: "Iron Howl",
    album: "Backlash",
  },
  {
    track: "angry_3.mp3",
    mood: "Angry",
    genre: "Metal",
    tempo: "Fast",
    era: "2000s-2010s",
    artist: "Metal Surge",
    album: "Dark Voltage",
  },
  {
    track: "angry_4.mp3",
    mood: "Angry",
    genre: "Rock",
    tempo: "Fast",
    era: "80-90s",
    artist: "Stone Riot",
    album: "Rebel Yell",
  },
  {
    track: "angry_5.mp3",
    mood: "Angry",
    genre: "Hip Hop",
    tempo: "Fast",
    era: "Recent",
    artist: "Raw Vibe",
    album: "Unfiltered",
  },

  // Energetic Tracks
  {
    track: "energetic_1.mp3",
    mood: "Energetic",
    genre: "Pop",
    tempo: "Fast",
    era: "Recent",
    artist: "Pulsebeat",
    album: "Jumpstart",
  },
  {
    track: "energetic_2.mp3",
    mood: "Energetic",
    genre: "Pop",
    tempo: "Medium",
    era: "2000s-2010s",
    artist: "Neon Steps",
    album: "Feel Good",
  },
  {
    track: "energetic_3.mp3",
    mood: "Energetic",
    genre: "Pop",
    tempo: "Fast",
    era: "80-90s",
    artist: "Flashwave",
    album: "Hype Nation",
  },
  {
    track: "energetic_4.mp3",
    mood: "Energetic",
    genre: "Pop",
    tempo: "Fast",
    era: "Recent",
    artist: "Voltage Vibes",
    album: "Electric Heart",
  },
  {
    track: "energetic_5.mp3",
    mood: "Energetic",
    genre: "Pop",
    tempo: "Medium",
    era: "2000s-2010s",
    artist: "Sky Pulse",
    album: "Motion",
  },

  // Focused Tracks
  {
    track: "focused_1.mp3",
    mood: "Focused",
    genre: "Classical",
    tempo: "Slow",
    era: "80-90s",
    artist: "Clara DeLune",
    album: "Quiet Mind",
  },
  {
    track: "focused_2.mp3",
    mood: "Focused",
    genre: "Classical",
    tempo: "Medium",
    era: "2000s-2010s",
    artist: "Echo Keys",
    album: "Deep Flow",
  },
  {
    track: "focused_3.mp3",
    mood: "Focused",
    genre: "Classical",
    tempo: "Slow",
    era: "2000s-2010s",
    artist: "Theo Strings",
    album: "Concentration Suite",
  },
  {
    track: "focused_4.mp3",
    mood: "Focused",
    genre: "Classical",
    tempo: "Slow",
    era: "80-90s",
    artist: "Isabella Harmonique",
    album: "Stillness",
  },
  {
    track: "focused_5.mp3",
    mood: "Focused",
    genre: "Classical",
    tempo: "Medium",
    era: "2000s-2010s",
    artist: "Ava Corelli",
    album: "Structured Silence",
  },

  // Happy Tracks
  {
    track: "happy_1.mp3",
    mood: "Happy",
    genre: "Pop",
    tempo: "Fast",
    era: "Recent",
    artist: "Sunset Groove",
    album: "Good Vibes Only",
  },
  {
    track: "happy_2.mp3",
    mood: "Happy",
    genre: "Pop",
    tempo: "Medium",
    era: "2000s-2010s",
    artist: "Joy Parade",
    album: "Bright Days",
  },
  {
    track: "happy_3.mp3",
    mood: "Happy",
    genre: "Pop",
    tempo: "Fast",
    era: "80-90s",
    artist: "Shiny Beats",
    album: "Smile Back",
  },
  {
    track: "happy_4.mp3",
    mood: "Happy",
    genre: "Pop",
    tempo: "Fast",
    era: "Recent",
    artist: "Golden Aura",
    album: "Energize",
  },
  {
    track: "happy_5.mp3",
    mood: "Happy",
    genre: "Pop",
    tempo: "Medium",
    era: "2000s-2010s",
    artist: "Bounce Mode",
    album: "Perk Up",
  },

  // Melancholic Tracks
  {
    track: "melancholic_1.mp3",
    mood: "Melancholic",
    genre: "Jazz",
    tempo: "Slow",
    era: "80-90s",
    artist: "Blue Tone",
    album: "Evening Fade",
  },
  {
    track: "melancholic_2.mp3",
    mood: "Melancholic",
    genre: "Classical",
    tempo: "Slow",
    era: "Recent",
    artist: "Eleanor Keys",
    album: "Reflections",
  },
  {
    track: "melancholic_3.mp3",
    mood: "Melancholic",
    genre: "Jazz",
    tempo: "Slow",
    era: "2000s-2010s",
    artist: "Soul Mist",
    album: "Twilight Talk",
  },
  {
    track: "melancholic_4.mp3",
    mood: "Melancholic",
    genre: "Jazz",
    tempo: "Medium",
    era: "80-90s",
    artist: "Slow Drift",
    album: "Late Night",
  },
  {
    track: "melancholic_5.mp3",
    mood: "Melancholic",
    genre: "Jazz",
    tempo: "Slow",
    era: "80-90s",
    artist: "Jazzy Echo",
    album: "Sighs & Sax",
  },

  // Peaceful Tracks
  {
    track: "peaceful_1.mp3",
    mood: "Peaceful",
    genre: "Classical",
    tempo: "Slow",
    era: "80-90s",
    artist: "Nina Waltz",
    album: "Peace Within",
  },
  {
    track: "peaceful_2.mp3",
    mood: "Peaceful",
    genre: "Jazz",
    tempo: "Slow",
    era: "Recent",
    artist: "Soft Tempo",
    album: "Mellow Minds",
  },
  {
    track: "peaceful_3.mp3",
    mood: "Peaceful",
    genre: "Classical",
    tempo: "Slow",
    era: "2000s-2010s",
    artist: "Lucia Notes",
    album: "Inner Still",
  },
  {
    track: "peaceful_4.mp3",
    mood: "Peaceful",
    genre: "Classical",
    tempo: "Slow",
    era: "80-90s",
    artist: "Nocturne",
    album: "Silent Waters",
  },
  {
    track: "peaceful_5.mp3",
    mood: "Peaceful",
    genre: "Classical",
    tempo: "Slow",
    era: "2000s-2010s",
    artist: "Mira Tone",
    album: "Lull Flow",
  },

  // Relaxed Tracks
  {
    track: "relaxed_1.mp3",
    mood: "Relaxed",
    genre: "Classical",
    tempo: "Slow",
    era: "80-90s",
    artist: "Harmony Lake",
    album: "Calm Currents",
  },
  {
    track: "relaxed_2.mp3",
    mood: "Relaxed",
    genre: "Jazz",
    tempo: "Slow",
    era: "2000s-2010s",
    artist: "Cool Flow",
    album: "Lounge Ease",
  },
  {
    track: "relaxed_3.mp3",
    mood: "Relaxed",
    genre: "Classical",
    tempo: "Medium",
    era: "2000s-2010s",
    artist: "Celia Harmonics",
    album: "Tranquil Theory",
  },
  {
    track: "relaxed_4.mp3",
    mood: "Relaxed",
    genre: "Jazz",
    tempo: "Medium",
    era: "80-90s",
    artist: "Mild Rhythm",
    album: "Soft Side",
  },
  {
    track: "relaxed_5.mp3",
    mood: "Relaxed",
    genre: "Jazz",
    tempo: "Slow",
    era: "80-90s",
    artist: "Jazz Float",
    album: "Unwind",
  },

  // Romantic Tracks
  {
    track: "romantic_1.mp3",
    mood: "Romantic",
    genre: "Jazz",
    tempo: "Slow",
    era: "80-90s",
    artist: "Velvet Keys",
    album: "Hearts Aligned",
  },
  {
    track: "romantic_2.mp3",
    mood: "Romantic",
    genre: "Classical",
    tempo: "Slow",
    era: "Recent",
    artist: "Luna Cello",
    album: "Whispers of Love",
  },
  {
    track: "romantic_3.mp3",
    mood: "Romantic",
    genre: "Jazz",
    tempo: "Slow",
    era: "2000s-2010s",
    artist: "Romantique",
    album: "Candlelight",
  },
  {
    track: "romantic_4.mp3",
    mood: "Romantic",
    genre: "Jazz",
    tempo: "Medium",
    era: "80-90s",
    artist: "Sapphire Soul",
    album: "Sweet Escape",
  },
  {
    track: "romantic_5.mp3",
    mood: "Romantic",
    genre: "Jazz",
    tempo: "Slow",
    era: "2000s-2010s",
    artist: "Blue Velvet",
    album: "Slow Burn",
  },
];
